apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 700-cp4s-multicloud
  labels:
    type: software
    platform: ibm
    code: '700'
  annotations:
    displayName: IBM Cloud Pak for Security
    description: >-
      Populates a GitOps repository with the components of IBM Cloud Pak for
      Security
spec:
  modules:
    - name: gitops-cp-catalogs
      alias: gitops-cp-catalogs
      version: v1.2.4
      variables:
        - name: entitlement_key
          scope: global
    - name: gitops-cp4s
      alias: gitops-cp4s
      version: v1.1.1
      dependencies:
        - name: namespace
          ref: cp4s-namespace
      variables:
        - name: storage_class
          alias: rwo_storage_class
          scope: global
        - name: backup_storage_class
          alias: rwo_storage_class
          scope: global
        - name: roks_auth
          value: false
    - name: gitops-namespace
      alias: cp4s-namespace
      version: v1.12.1
      variables:
        - name: name
          value: cp4s
    - name: gitops-repo
      alias: gitops_repo
      version: v1.21.0
  variables:
    - name: entitlement_key
      type: string
      description: >-
        The entitlement key used to access the CP4I images in the container
        registry. Visit https://myibm.ibm.com/products-services/containerlibrary
        to get the key
      sensitive: true
    - name: gitops-cp4s_admin_user
      type: string
      description: >-
        Short name or email-id of the user to be given administrator privileges
        in the default account. Mandatory value while creating
        cp4s-threat-management-instance
    - name: gitops_repo_host
      type: string
      description: >-
        The host for the git repository. The git host used can be a GitHub,
        GitHub Enterprise, Gitlab, Bitbucket, Gitea or Azure DevOps server. If
        the host is null assumes in-cluster Gitea instance will be used.
      defaultValue: ''
    - name: gitops_repo_org
      type: string
      description: >-
        The org/group where the git repository exists/will be provisioned. If
        the value is left blank then the username org will be used.
      defaultValue: ''
    - name: gitops_repo_project
      type: string
      description: >-
        The project that will be used for the git repo. (Primarily used for
        Azure DevOps repos)
      defaultValue: ''
    - name: gitops_repo_username
      type: string
      description: The username of the user with access to the repository
      defaultValue: ''
    - name: gitops_repo_token
      type: string
      description: The personal access token used to access the repository
      defaultValue: ''
      sensitive: true
    - name: gitops_repo_repo
      type: string
      description: >-
        The short name of the repository (i.e. the part after the org/group
        name)
